name: Integration Tests

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  workflow_dispatch:
  pull_request:
    branches:
      [ main, develop ]

permissions:
  contents: read

jobs:
  build-jar:
    runs-on: ubuntu-latest
    name: Build JAR and Upload Artifact
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Prepare Artifacts
        run: |
          mkdir -p artifacts/osx artifacts/windows artifacts/linux
          cp cli/target/buildcli.jar artifacts/
          cp -r scripts/* artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: buildcli-artifacts
          path: artifacts/

  integration-tests:
    needs: build-jar
    strategy:
      matrix:
        java: [ 21 ]
        java-distribution: [ temurin ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    name: Test BuildCLI (Java ${{ matrix.java }} ${{ matrix.java-distribution }} - ${{ matrix.os }})
    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.java-distribution }}

      - name: Download Artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: buildcli-artifacts
          path: artifacts/

      - name: Verify BuildCLI installation on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          cp artifacts/buildcli.jar artifacts/linux/
          chmod +x artifacts/linux/buildcli
          if ! ./artifacts/linux/buildcli version; then
            echo "BuildCLI command not found or failed to execute."
            exit 1
          fi

      - name: Verify BuildCLI installation on macOS
        if: matrix.os == 'macos-latest'
        run: |
          cp artifacts/buildcli.jar artifacts/osx/
          chmod +x artifacts/osx/buildcli
          if ! ./artifacts/osx/buildcli version; then
          echo "BuildCLI command not found or failed to execute."
          exit 1
          fi

      - name: Verify BuildCLI installation on Windows
        if: matrix.os == 'windows-latest'
        run: |
          cp artifacts\buildcli.jar artifacts\windows\
          if (-not (artifacts\windows\buildcli.bat version)) {
          Write-Error "BuildCLI command not found or failed to execute."
          exit 1
          }
