name: Release Build and Upload

on:
  release:
    types: [published]

permissions:
  contents: write


jobs:
  build-jar:
    runs-on: ubuntu-latest
    name: Build JAR and Upload Artifact
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build JAR
        run: mvn clean package -DskipTests
      - name: Prepare Artifacts
        run: |
          mkdir -p artifacts/osx artifacts/windows artifacts/linux
          ln cli/target/buildcli.jar artifacts/linux/
          ln cli/target/buildcli.jar artifacts/osx/
          ln cli/target/buildcli.jar artifacts/windows/
          cp -r scripts/* artifacts/

      - name: Compress Artifacts
        run: |
          cd artifacts
          zip -r linux.zip linux
          zip -r osx.zip osx
          zip -r windows.zip windows
          tar -czvf linux.tar.gz linux
          tar -czvf osx.tar.gz osx
          tar -czvf windows.tar.gz windows

      - name: Upload Artifacts
        run: gh release upload ${{ github.event.release.tag_name }} artifacts/linux.zip artifacts/osx.zip artifacts/windows.zip artifacts/linux.tar.gz artifacts/osx.tar.gz artifacts/windows.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}
